apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube
  template: 
    metadata:  
      labels:
        app: kube
    spec:
      containers:
      - name: kube-site
        image: especialistascloud/kubenews:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-kube
spec:
  selector:
    app: kub
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort